-- Primero eliminamos la tabla si existe
DROP TABLE IF EXISTS public.catas;

-- Creamos la tabla con una clave primaria compuesta
CREATE TABLE public.catas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL,
    ron TEXT NOT NULL,
    pureza INTEGER,
    olfato_intensidad INTEGER,
    olfato_complejidad INTEGER,
    gusto_intensidad INTEGER,
    gusto_complejidad INTEGER,
    gusto_persistencia INTEGER,
    armonia INTEGER,
    total INTEGER,
    notas TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (nombre, ron)  -- Clave primaria compuesta
);

-- Creamos índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_catas_nombre ON public.catas (nombre);
CREATE INDEX IF NOT EXISTS idx_catas_ron ON public.catas (ron);
CREATE INDEX IF NOT EXISTS idx_catas_timestamp ON public.catas (timestamp);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.catas ENABLE ROW LEVEL SECURITY;

-- Permitir acceso a todos (ajusta esto según tus necesidades de seguridad)
CREATE POLICY "Allow all" ON public.catas FOR ALL USING (true); 